FROM apache/airflow:2.9.3-python3.11

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    libmariadb-dev \
    libmariadb3 \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

RUN pip install --no-cache-dir \
    mariadb \
    PyMySQL \
    cryptography \
    mlflow \
    pandas \
    numpy \
    scikit-learn \
    joblib \
    sqlalchemy \
    redis \
    evidently \
    fastapi \
    uvicorn \
    pydantic